name: Create Synapse Credential (simple)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options: [dev, test, stage, prod, nonprd]
        default: nonprd

jobs:
  create-credential:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Uses your existing SPN JSON (env secret) to log in
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create/Update Synapse credential (curl)
        shell: bash
        env:
          WS:   ${{ vars.SYNAPSE_WORKSPACE_NAME }}   # e.g. synapsewsdemo123
          CRED: ${{ vars.CREDENTIAL_NAME }}          # e.g. mpe-uai-cred
          UAMI: ${{ vars.UAMI_RESOURCE_ID }}         # full resourceId of your UAMI
        run: |
          set -euo pipefail

          # Get a data-plane token
          TOKEN=$(az account get-access-token --scope https://dev.azuresynapse.net/.default --query accessToken -o tsv)
          echo "::add-mask::$TOKEN"

          URI="https://${WS}.dev.azuresynapse.net/credentials/${CRED}?api-version=2020-12-01"

          # --- CREATE/UPDATE (PUT) ---
          curl -sS -i -X PUT \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -H "If-Match: *" \
            --data "{
              \"properties\": {
                \"type\": \"ManagedIdentity\",
                \"typeProperties\": { \"resourceId\": \"${UAMI}\" },
                \"description\": \"Created by GitHub Actions (simple)\"
              }
            }" \
            "$URI"

          # --- VERIFY (GET has no body) ---
          echo -e "\n\nVerifying..."
          curl -sS -H "Authorization: Bearer $TOKEN" "$URI"

      # (Optional) If your workspace blocks public IPs, open/close a temp rule here.
