name: Create Synapse Credential (curl-mini)

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [dev, test, stage, prod, nonprd]
        default: nonprd

jobs:
  create-cred:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Optional but prevents InvalidUserAssignedMiCredential
      - name: Attach UAMI to workspace (idempotent)
        env:
          RG:   ${{ vars.RESOURCE_GROUP }}
          WS:   ${{ vars.SYNAPSE_WORKSPACE_NAME }}
          UAMI: ${{ vars.UAMI_RESOURCE_ID }}
        run: |
          set -e
          WSID=$(az synapse workspace show -g "$RG" -n "$WS" --query id -o tsv)
          az resource update --ids "$WSID" --set identity.type="SystemAssigned,UserAssigned" >/dev/null
          az resource update --ids "$WSID" --set identity.userAssignedIdentities."$UAMI"={} >/dev/null

      - name: PUT credential with curl
        env:
          WS:   ${{ vars.SYNAPSE_WORKSPACE_NAME }}
          CRED: ${{ vars.CREDENTIAL_NAME }}
          UAMI: ${{ vars.UAMI_RESOURCE_ID }}
        run: |
          set -e
          TOKEN=$(az account get-access-token --scope https://dev.azuresynapse.net/.default --query accessToken -o tsv)
          URI="https://${WS}.dev.azuresynapse.net/credentials/${CRED}?api-version=2020-12-01"
          BODY='{"properties":{"type":"ManagedIdentity","typeProperties":{"resourceId":"'"$UAMI"'"}}}'

          # Create/Update
          curl -sS -X PUT \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -H "If-Match: *" \
            --data "$BODY" \
            "$URI"

          # Verify (GET has no body)
          echo -e "\nVerifying..."
          curl -sS -H "Authorization: Bearer $TOKEN" "$URI"
