name: Create Synapse Credential (curl-mini)

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [dev, test, stage, prod, nonprd]
        default: nonprd

jobs:
  create-cred:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: PUT credential with curl
        env:
          WS:   ${{ vars.SYNAPSE_WORKSPACE_NAME }}   # e.g. synapsewsdemo123
          CRED: ${{ vars.CREDENTIAL_NAME }}          # e.g. mpe-uai-cred
          UAMI: ${{ vars.UAMI_RESOURCE_ID }}         # full resourceId of the UAMI
        run: |
          set -e
          TOKEN=$(az account get-access-token --scope https://dev.azuresynapse.net/.default --query accessToken -o tsv)
          URI="https://${WS}.dev.azuresynapse.net/credentials/${CRED}?api-version=2020-12-01"
          BODY='{
            "properties": {
              "type": "ManagedIdentity",
              "typeProperties": {
                "resourceId": "'"$UAMI"'"
              }
            }
          }'

          curl -sS -X PUT \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -H "If-Match: *" \
            --data "$BODY" \
            "$URI"
