name: Deploy Azure Resources with Bicep

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: "Environment to deploy (nonprod or prod)"
        required: true
        type: choice
        options:
          - nonprod
          - prod
        default: nonprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: az bicep install
      - name: Deploy Bicep Template
        env:
          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
        run: |
          set -x
          az deployment group create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --template-file ./main.bicep