name: Deploy Managed Private Endpoints for Synapse

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment folder to deploy from"
        required: true
        type: choice
        options:
          - dev
          - test
          - stage
          - prod
          - nonprod
        default: nonprd

jobs:
  deploy-mpes:
    name: Deploy MPEs to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PowerShell Core
        uses: PowerShell/Setup-PowerShell@v1
        with:
          pwsh-version: '7.2.x'

      - name: Install Az PowerShell module
        run: |
          pwsh -Command 'Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser'

      - name: Verify input and folder
        run: |
          echo "🔍 Validating input: ${{ inputs.environment }}"
          ls ./configs/managedPrivateEndpoints/${{ inputs.environment }} || echo "⚠️ Folder empty or not found"
