name: Deploy Managed Private Endpoints for Synapse Workspace

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy."
        type: choice
        required: true
        options:
          - dev
          - test
          - nonprd
          - stage
          - prod
        default: nonprd

jobs:
  deploy-endpoints:
    runs-on:
      group: azure-large-runners
      labels: ubuntu-azure-large
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Az PowerShell Module
        run: |
          pwsh -Command 'Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force'

      - name: Ensure Environment Directory Exists
        run: |
          if [ ! -d "./configs/managedprivateendpoints/${{ github.event.inputs.environment }}" ]; then
            echo "Environment directory does not exist!"
            exit 1
          fi

      - name: List Config Files
        run: |
          ls ./configs/managedprivateendpoints/${{ github.event.inputs.environment }} || echo "No JSON files found"

      - name: Debug Environment Folder
        run: |
          echo "Using environment folder: ./configs/managedprivateendpoints/${{ github.event.inputs.environment }}"

      - name: Verify Azure Credentials
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "Azure credentials are missing!"
            exit 1
          fi

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Managed Private Endpoint Deployment Script
        run: |
          pwsh ./scripts/AddManagedPrivateEndpoints.ps1 -environmentFolder "./configs/managedprivateendpoints/${{ github.event.inputs.environment }}"

      - name: Debug - List Directory Contents
        run: |
          ls ./configs/managedprivateendpoints/${{ github.event.inputs.environment }} || echo "No directory found"

      - name: Debug - Check for JSON Files
        run: |
          ls ./configs/managedprivateendpoints/${{ github.event.inputs.environment }}/*.json || echo "No JSON files present"

      - name: Debug - Show Azure Context
        run: |
          pwsh -Command 'Get-AzContext'
