name: Deploy Managed Private Endpoints for Synapse

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment folder to deploy from"
        required: true
        type: choice
        options:
          - dev
          - test
          - stage
          - prod
          - nonprd
        default: nonprd

jobs:
  deploy-mpes:
    name: Deploy MPEs
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display PowerShell version
        run: pwsh -Command '$PSVersionTable.PSVersion'

      - name: Install Az PowerShell module
        run: pwsh -Command 'Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser'

      - name: Run PowerShell script to deploy MPEs
        run: |
          pwsh ./scripts/Deploy-MPEs.ps1 -EnvironmentFolder "${{ inputs.environment }}"
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          SYNAPSE_WORKSPACE_NAME: ${{ vars.SYNAPSE_WORKSPACE_NAME }}
