name: Deploy Synapse Managed Private Endpoints

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - nonprd
          - prod
        default: nonprd

jobs:
  deploy:
    name: Deploy MPEs to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Az PowerShell module
        run: pwsh -Command 'Install-Module -Name Az -Scope CurrentUser -Force -AllowClobber'

      - name: Run PowerShell script to deploy MPEs
        run: pwsh -File ./scripts/Deploy-MPEs.ps1 -EnvironmentFolder "${{ inputs.environment }}" -SynapseWorkspaceName "synapsewsdemo123"
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
